export const APPOINTMENT_ACTION_TYPE = {
  BOOK_APPOINTMENT_REQUEST: 'BOOK_APPOINTMENT_REQUEST',
  BOOK_APPOINTMENT_SUCCESS: 'BOOK_APPOINTMENT_SUCCESS',
  BOOK_APPOINTMENT_FAILURE: 'BOOK_APPOINTMENT_FAILURE',

  // get upcoming Appointment

  GET_UPCOMING_APPOINTMENT_REQUEST: 'GET_UPCOMING_APPOINTMENT_REQUEST',
  GET_UPCOMING_APPOINTMENT_SUCCESS: 'GET_UPCOMING_APPOINTMENT_SUCCESS',
  GET_UPCOMING_APPOINTMENT_FAILURE: 'GET_UPCOMING_APPOINTMENT_FAILURE',
};
