export const AUTH_ACTION_TYPE = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // check account

  CHECK_ACCOUNT_REQUEST: 'CHECK_ACCOUN_REQUEST',
  CHECK_ACCOUN_SUCCESS: 'CHECK_ACCOUN_SUCCESS',
  CHECK_ACCOUN_FAILURE: 'CHECK_ACCOUN_FAILURE',

  // get otp

  GET_OTP_REQUEST: 'GET_OTP_REQUEST',
  GET_OTP_SUCCESS: 'GET_OTP_SUCCESS',
  GET_OTP_FAILURE: 'GET_OTP_FAILURE',

  // verify otp
  VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',
};
