export const COMMON_ACTION_TYPE = {
  GET_USER_ID_REQUEST: 'GET_USER_IDREQUEST',
  GET_USER_ID_SUCCESS: 'GET_USER_ID_SUCCESS',
  GET_USER_ID_FAILURE: 'GET_USER_ID_FAILURE',

  /// get time slot

  GET_TIME_SLOT_REQUEST: 'GET_TIME_SLOT_REQUEST',
  GET_TIME_SLOT_SUCCESS: 'GET_TIME_SLOT_SUCCESS',
  GET_TIME_SLOT_FAILURE: 'GET_TIME_SLOT_FAILURE',

  // get common details for term and condition
  GET_COMMON_TERMAND_CONDITION_REQUEST: 'GET_COMMON_TERMAND_CONDITION_REQUEST',
  GET_COMMON_TERMAND_CONDITION_SUCCESS: 'GET_COMMON_TERMAND_CONDITION_SUCCESS',
  GET_COMMON_TERMAND_CONDITION_FAILURE: 'GET_COMMON_TERMAND_CONDITION_FAILURE',
};
