export const PAYMENT_ACTION_TYPE = {
  // post Transtaction stattus

  POST_PAYMENT_DETAIL_REQUEST: 'POST_PAYMENT_DETAIL_REQUEST',
  POST_PAYMENT_DETAIL_SUCCESS: 'POST_PAYMENT_DETAIL_SUCCESS',
  POST_PAYMENT_DETAIL_FAILURE: 'POST_PAYMENT_DETAIL_FAILURE',
};
