export const USER_DETAILS_ACTION_TYPE = {
    POST_STUDENT_INFO_REQUEST: 'POST_STUDENT_INFO_REQUEST',
    POST_STUDENT_INFO_SUCCESS: 'POST_STUDENT_INFO_SUCCESS',
    POST_STUDENT_INFO_FAILURE: 'POST_STUDENT_INFO_FAILURE',

// post student qualification 

POST_STUDENT_QUALIFICTION_REQUEST: 'POST_STUDENT_QUALIFICTION_REQUEST',
POST_STUDENT_QUALIFICTION_SUCCESS: 'POST_STUDENT_QUALIFICTION_SUCCESS',
POST_STUDENT_QUALIFICTION_FAILURE: 'POST_STUDENT_QUALIFICTION_FAILURE',

// WORK EXP
POST_STUDENT_WORK_EXP_REQUEST: 'POST_STUDENT_WORK_EXP_REQUEST',
POST_STUDENT_WORK_EXP_SUCCESS: 'POST_STUDENT_WORK_EXP_SUCCESS',
POST_STUDENT_WORK_EXP_FAILURE: 'POST_STUDENT_WORK_EXP_FAILURE',

// merital status
POST_STUDENT_MERITAL_STATUS_REQUEST: 'POST_STUDENT_MERITAL_STATUS_REQUEST',
POST_STUDENT_MERITAL_STATUS_SUCCESS: 'POST_STUDENT_MERITAL_STATUS_SUCCESS',
POST_STUDENT_MERITAL_STATUS_FAILURE: 'POST_STUDENT_MERITAL_STATUS_FAILURE',


//ielts

POST_STUDENT_IELTS_REQUEST: 'POST_STUDENT_IELTS_REQUEST',
POST_STUDENT_IELTS_SUCCESS: 'POST_STUDENT_IELTS_SUCCESS',
POST_STUDENT_IELTS_FAILURE: 'POST_STUDENT_IELTS_FAILURE',

// pre refusal 

POST_STUDENT_PRE_REFUSAL_REQUEST: 'POST_STUDENT_PRE_REFUSAL_REQUEST',
POST_STUDENT_PRE_REFUSAL_SUCCESS: 'POST_STUDENT_PRE_REFUSAL_SUCCESS',
POST_STUDENT_PRE_REFUSAL_FAILURE: 'POST_STUDENT_PRE_REFUSAL_FAILURE',

// get student info 

GET_STUDENT_INFO_REQUEST: 'GET_STUDENT_INFO_REQUEST',
GET_STUDENT_INFO_SUCCESS: 'GET_STUDENT_INFO_SUCCESS',
GET_STUDENT_INFO_FAILURE: 'GET_STUDENT_INFO_FAILURE',

// get student qulification


GET_STUDENT_QUALIFICTION_REQUEST: 'GET_STUDENT_QUALIFICTION_REQUEST',
GET_STUDENT_QUALIFICTION_SUCCESS: 'GET_STUDENT_QUALIFICTION_SUCCESS',
GET_STUDENT_QUALIFICTION_FAILURE: 'GET_STUDENT_QUALIFICTION_FAILURE',

//get student work experiance
GET_STUDENT_WORK_EXP_REQUEST: 'GET_STUDENT_WORK_EXP_REQUEST',
GET_STUDENT_WORK_EXP_SUCCESS: 'GET_STUDENT_WORK_EXP_SUCCESS',
GET_STUDENT_WORK_EXP_FAILURE: 'GET_STUDENT_WORK_EXP_FAILURE',

// get student merital status

GET_STUDENT_MERITAL_STATUS_REQUEST: 'GET_STUDENT_MERITAL_STATUS_REQUEST',
GET_STUDENT_MERITAL_STATUS_SUCCESS: 'GET_STUDENT_MERITAL_STATUS_SUCCESS',
GET_STUDENT_MERITAL_STATUS_FAILURE: 'GET_STUDENT_MERITAL_STATUS_FAILURE',

// get ielts

GET_STUDENT_IELTS_REQUEST: 'GET_STUDENT_IELTS_REQUEST',
GET_STUDENT_IELTS_SUCCESS: 'GET_STUDENT_IELTS_SUCCESS',
GET_STUDENT_IELTS_FAILURE: 'GET_STUDENT_IELTS_FAILURE',

// get previous refusal 

GET_STUDENT_PRE_REFUSAL_REQUEST: 'GET_STUDENT_PRE_REFUSAL_REQUEST',
GET_STUDENT_PRE_REFUSAL_SUCCESS: 'GET_STUDENT_PRE_REFUSAL_SUCCESS',
GET_STUDENT_PRE_REFUSAL_FAILURE: 'GET_STUDENT_PRE_REFUSAL_FAILURE',

}